#!/data/data/com.termux/files/usr/bin/bash
# Install api-content-prod boot script for Termux:Boot (phone-a fallback).
set -euo pipefail

BOOT_DEST="$HOME/.termux/boot/start-content-phone-a.sh"
CONTENT="$HOME/phone-lab/packages/api-content-prod/scripts/termux/phone-b"

mkdir -p "$HOME/.termux/boot"

cat > "$BOOT_DEST" << EOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install-boot-content-phone-a.sh
set -euo pipefail
sleep 50
DATA_PLANE="$HOME/phone-lab/packages/api-content-prod/scripts/termux/phone-a/setup-content-data-plane.sh"
if [ -f "\$DATA_PLANE" ]; then
  bash "\$DATA_PLANE" || true
fi
if [ -f "$CONTENT/restart-content-prod.sh" ]; then
  bash "$CONTENT/restart-content-prod.sh" || true
fi
EOF

chmod +x "$BOOT_DEST"
DATA_PLANE_SRC="$HOME/phone-lab/packages/api-content-prod/scripts/termux/phone-a/setup-content-data-plane.sh"
if [ -f "$DATA_PLANE_SRC" ]; then
  chmod +x "$DATA_PLANE_SRC"
fi
echo "Installed: $BOOT_DEST"
