#!/data/data/com.termux/files/usr/bin/bash
# Install api-content-prod boot script for Termux:Boot (optional; main boot via agents stack).
set -euo pipefail

BOOT_DEST="$HOME/.termux/boot/start-content-phone-b.sh"
CONTENT="$HOME/phone-lab/packages/api-content-prod/scripts/termux/phone-b"

mkdir -p "$HOME/.termux/boot"

cat > "$BOOT_DEST" << EOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by install-boot-content.sh
sleep 45
if [ -x "$CONTENT/restart-content-prod.sh" ]; then
  bash "$CONTENT/restart-content-prod.sh" || true
fi
EOF

chmod +x "$BOOT_DEST"
echo "Installed: $BOOT_DEST"
