#!/data/data/com.termux/files/usr/bin/bash
# Install ~/.bashrc + ~/.profile hook: start phone-lab stack when Termux opens.
# Usage: bash install-termux-login-hook.sh phone-a|phone-b
set -euo pipefail

PHONE="${1:-}"
case "$PHONE" in
  phone-a|phone-b) ;;
  *)
    echo "Usage: $0 phone-a|phone-b"
    exit 1
    ;;
esac

SESSION_SCRIPT="$HOME/phone-lab/scripts/termux/$PHONE/session-start-$PHONE.sh"
LOCK_FILE="$HOME/phone-lab/data/session-start.lock"
MARKER_BEGIN="# >>> phone-lab session-start >>>"
MARKER_END="# <<< phone-lab session-start <<<"

if [ ! -f "$SESSION_SCRIPT" ]; then
  echo "ERROR: missing $SESSION_SCRIPT — deploy session-start scripts first"
  exit 1
fi

mkdir -p "$HOME/phone-lab/data" "$HOME/phone-lab/logs"
touch "$LOCK_FILE"

HOOK_BLOCK="${MARKER_BEGIN}
# Auto-generated by install-termux-login-hook.sh — do not edit manually
PHONE_LAB_SESSION_START=\"$SESSION_SCRIPT\"
PHONE_LAB_SESSION_LOCK=\"$LOCK_FILE\"
# SSH first so dev PC can connect while stack starts in background
if command -v sshd >/dev/null 2>&1 && ! pgrep -x sshd >/dev/null 2>&1; then
  sshd
fi
if [ -f \"\$PHONE_LAB_SESSION_START\" ]; then
  bash \"\$PHONE_LAB_SESSION_START\" &
fi
${MARKER_END}"

install_hook_into() {
  local rc_file="$1"
  local tmp
  tmp="$(mktemp)"

  if [ -f "$rc_file" ]; then
    awk -v begin="$MARKER_BEGIN" -v end="$MARKER_END" '
      $0 == begin { skip=1; next }
      $0 == end { skip=0; next }
      !skip { print }
    ' "$rc_file" >"$tmp"
    mv "$tmp" "$rc_file"
  else
    : >"$rc_file"
  fi

  printf '\n%s\n' "$HOOK_BLOCK" >>"$rc_file"
  echo "Updated: $rc_file"
}

install_hook_into "$HOME/.bashrc"
install_hook_into "$HOME/.profile"

echo ""
echo "Installed Termux login hook for $PHONE"
echo "  session: $SESSION_SCRIPT"
echo "  log:     $HOME/phone-lab/logs/session-start.log"
echo ""
echo "When you open Termux after closing it, the stack starts in the background (~1–2 min)."
echo "Optional: termux-wake-lock keeps CPU awake while charging."
